# TÃ­tulo do Projeto: Apresentacao

## DescriÃ§Ã£o ğŸ“–
Este vÃ­deo de 3 segundos faz uma apresentaÃ§Ã£o rÃ¡pida de uma estudante em primeiro contato com criaÃ§Ã£o de vÃ­deo utilizando IA.

## Tecnologias Utilizadas ğŸš€
 IA Generativa **[ChatGPT](https://chat.openai.com)** para roteirizaÃ§Ã£o e revisÃ£o.
 IA Generativa **[D-ID](https://www.d-id.com)** para geraÃ§Ã£o de avatar virtual.

## Processo de CriaÃ§Ã£o ğŸ‘¨â€ğŸ’»ğŸ‘©â€ğŸ’»
Usei o "ChatGPT" para escrever e revisar o roteiro do vÃ­deo, mas o "D-ID" nÃ£o permitiu muitas palavras. O "D-ID" foi essencial para criar um avatar virtual.

## Resultados: ğŸ¤“ ou ğŸ¤–
O vÃ­deo traz uma apresentaÃ§Ã£o rÃ¡pida do avatar como teste da ferramenta.
[https://studio.d-id.com/share?id=05a7198ddfd91e6b7a34d1559ab36506&utm_source=copy]()

## ReflexÃ£o (Opcional) ğŸ¤”
Este projeto foi uma experiÃªncia legal de um primeiro contato com criaÃ§Ã£o de vÃ­deo utilizando IA Generativa.
